apiVersion: v1
kind: Service
metadata:
  name: final_project_backend
spec:
  selector:
    app: final_project_backend
  ports:
    - protocol: TCP
      port: 9500
      targetPort: 9500
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: final_project_backend
  labels:
    app: final_project_backend
spec:
  selector:
    matchLabels:
      app: final_project_backend
  template:
    metadata:
      labels:
        app: final_project_backend
    spec:
      containers:
        - name: final_project_backend
          image: judithed/final_project_backend:app_version
          ports:
            - containerPort: 9500