apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: judithed/backend:v70
          ports:
            - containerPort: 9500
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    service: backend
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9500
      targetPort: 9500
  selector:
    app: backend