apiVersion: v1
kind: Service
metadata:
  name: final_project_frontend
spec:
  selector:
    app: final_project_frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: final_project_frontend
  labels:
    app: final_project_frontend
spec:
  selector:
    matchLabels:
      app: final_project_frontend
  template:
    metadata:
      labels:
        app: final_project_frontend
    spec:
      containers:
        - name: final_project_frontend
          image: judithed/final_project_frontend:app_version
          ports:
            - containerPort: 3000