apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen 80;
      index index.html;
      location / {
          proxy_pass http://final_project_frontend:3000;
      }
    }